"use client";

export default function ServicesPage() {
  return (
    <section className="servicesPage">
      {/* HERO — CINEMATIC INTRO */}
      <div className="hero">
        <span className="tag">ARC3D EXPERIENCE ENGINE</span>

        <h1>
          Architecture is no longer
          <br />
          drawn — it is experienced.
        </h1>

        <p>
          Arc3D transforms static architectural thinking into living, responsive
          environments. Every wall, light, and material is simulated before
          construction begins — giving you the power to design reality before it
          exists.
        </p>
      </div>

      {/* DIVIDER STATEMENT */}
      <div className="statement">
        “We don’t design buildings. We simulate futures.”
      </div>

      {/* CORE EXPERIENCE GRID */}
      <div className="experience">
        <div className="expCard">
          <span>01</span>
          <h2>Spatial Intelligence Engine</h2>
          <p>
            Convert abstract 2D plans into intelligent 3D spatial systems that
            understand structure, flow, and human movement behavior.
          </p>
        </div>

        <div className="expCard">
          <span>02</span>
          <h2>AI Design Co-Pilot</h2>
          <p>
            Arc3D AI actively participates in design decisions — optimizing
            space, suggesting layouts, and predicting architectural efficiency.
          </p>
        </div>

        <div className="expCard">
          <span>03</span>
          <h2>Reality Simulation Layer</h2>
          <p>
            Simulate sunlight, shadows, materials, weather, and time —
            visualizing how architecture behaves in real conditions.
          </p>
        </div>
      </div>

      {/* FEATURE STORY SECTION */}
      <div className="featureStory">
        <div className="text">
          <h2>From Blueprint to Living World</h2>
          <p>
            Traditional architecture stops at visualization. Arc3D continues
            beyond it — generating dynamic environments that evolve as design
            decisions change. Every adjustment updates physics, lighting, and
            spatial flow instantly.
          </p>

          <ul>
            <li>Dynamic structural recalculation</li>
            <li>Real-time lighting physics</li>
            <li>Material intelligence system</li>
            <li>Human movement simulation</li>
          </ul>
        </div>

        <div className="visualBlock">
          <div className="glow"></div>
          <div className="mock">3D VIEWPORT</div>
        </div>
      </div>

      {/* PREMIUM SERVICES STRIP */}
      <div className="strip">
        <h2>Core Arc3D Modules</h2>

        <div className="stripGrid">
          <div className="miniCard">
            <h3>Blueprint AI Parser</h3>
            <p>Understands architectural intent from raw drawings.</p>
          </div>

          <div className="miniCard">
            <h3>Material Simulation Engine</h3>
            <p>Real-world physics for textures & surfaces.</p>
          </div>

          <div className="miniCard">
            <h3>Lighting Intelligence</h3>
            <p>Sun path + artificial lighting behavior modeling.</p>
          </div>

          <div className="miniCard">
            <h3>Walkthrough Generator</h3>
            <p>Cinematic camera paths auto-generated by AI.</p>
          </div>
        </div>
      </div>

      {/* SUBSCRIPTION SECTION (LUXURY SaaS STYLE) */}
      <div className="pricing">
        <h2>Membership Access</h2>

        <div className="plans">
          <div className="plan">
            <h3>Explorer</h3>
            <h1>Free</h1>
            <p>For students & learning</p>

            <ul>
              <li>Basic 3D conversion</li>
              <li>Limited AI suggestions</li>
              <li>Community access</li>
            </ul>

            <button>Start Exploring</button>
          </div>

          <div className="plan highlight">
            <h3>Architect</h3>
            <h1>₹1499</h1>
            <p>For professionals</p>

            <ul>
              <li>Full AI design engine</li>
              <li>Real-time simulation</li>
              <li>High-end rendering</li>
              <li>Cloud collaboration</li>
            </ul>

            <button>Most Chosen</button>
          </div>

          <div className="plan">
            <h3>Studio+</h3>
            <h1>₹4999</h1>
            <p>For firms & enterprises</p>

            <ul>
              <li>Unlimited projects</li>
              <li>Team system</li>
              <li>Priority compute</li>
              <li>API access</li>
            </ul>

            <button>Contact Sales</button>
          </div>
        </div>
      </div>

      {/* FINAL CTA */}
      <div className="cta">
        <h2>Build Something That Has Never Existed</h2>
        <p>Arc3D is not software — it is a new way of thinking about space.</p>

        <button>Enter Arc3D</button>
      </div>

      <style jsx>{`
        .servicesPage {
          padding: 140px 50px;
          background: #f3f1eb;
          color: #111;
        }

        /* HERO */
        .hero {
          max-width: 900px;
          margin: auto;
          text-align: center;
        }

        .tag {
          font-size: 11px;
          letter-spacing: 0.4em;
          color: rgba(0, 0, 0, 0.5);
        }

        .hero h1 {
          margin-top: 20px;
          font-size: 70px;
          line-height: 1.02;
          font-weight: 600;
        }

        .hero p {
          margin-top: 28px;
          font-size: 16px;
          line-height: 1.9;
          color: rgba(0, 0, 0, 0.65);
        }

        /* STATEMENT */
        .statement {
          margin-top: 120px;
          text-align: center;
          font-size: 20px;
          letter-spacing: 0.2em;
          color: rgba(0, 0, 0, 0.5);
        }

        /* EXPERIENCE */
        .experience {
          margin-top: 120px;
          display: grid;
          grid-template-columns: repeat(3, 1fr);
          gap: 24px;
        }

        .expCard {
          padding: 36px;
          border-radius: 26px;
          background: white;
          border: 1px solid rgba(0, 0, 0, 0.06);
          transition: 0.4s ease;
        }

        .expCard:hover {
          transform: translateY(-10px);
        }

        .expCard span {
          font-size: 12px;
          letter-spacing: 0.3em;
          color: rgba(0, 0, 0, 0.4);
        }

        .expCard h2 {
          margin-top: 16px;
          font-size: 22px;
        }

        .expCard p {
          margin-top: 14px;
          line-height: 1.7;
          color: rgba(0, 0, 0, 0.65);
        }

        /* FEATURE STORY */
        .featureStory {
          margin-top: 140px;
          display: grid;
          grid-template-columns: 1.2fr 0.8fr;
          gap: 60px;
          align-items: center;
        }

        .text h2 {
          font-size: 42px;
        }

        .text p {
          margin-top: 18px;
          line-height: 1.9;
          color: rgba(0, 0, 0, 0.65);
        }

        .text ul {
          margin-top: 20px;
          padding-left: 18px;
        }

        .visualBlock {
          height: 420px;
          border-radius: 28px;
          background: white;
          position: relative;
          overflow: hidden;
          border: 1px solid rgba(0, 0, 0, 0.06);
        }

        .mock {
          position: absolute;
          inset: 0;
          display: flex;
          align-items: center;
          justify-content: center;
          font-size: 18px;
          color: rgba(0, 0, 0, 0.3);
        }

        .glow {
          position: absolute;
          width: 300px;
          height: 300px;
          background: rgba(20, 40, 80, 0.1);
          filter: blur(80px);
          top: -80px;
          left: -80px;
        }

        /* STRIP */
        .strip {
          margin-top: 140px;
          text-align: center;
        }

        .stripGrid {
          margin-top: 50px;
          display: grid;
          grid-template-columns: repeat(4, 1fr);
          gap: 18px;
        }

        .miniCard {
          padding: 24px;
          background: white;
          border-radius: 20px;
        }

        /* PRICING */
        .pricing {
          margin-top: 140px;
          text-align: center;
        }

        .plans {
          margin-top: 60px;
          display: grid;
          grid-template-columns: repeat(3, 1fr);
          gap: 24px;
        }

        .plan {
          padding: 36px;
          background: white;
          border-radius: 28px;
        }

        .plan.highlight {
          border: 2px solid #111;
          transform: scale(1.05);
        }

        .plan h1 {
          font-size: 42px;
        }

        .plan ul {
          margin-top: 18px;
          text-align: left;
          padding-left: 18px;
        }

        .plan button {
          margin-top: 20px;
          width: 100%;
          padding: 14px;
          border-radius: 14px;
          border: none;
          background: #111;
          color: white;
        }

        /* CTA */
        .cta {
          margin-top: 140px;
          text-align: center;
        }

        .cta button {
          margin-top: 20px;
          padding: 14px 28px;
          border-radius: 14px;
          border: none;
          background: #111;
          color: white;
        }

        @media (max-width: 900px) {
          .experience,
          .stripGrid,
          .plans {
            grid-template-columns: 1fr;
          }

          .featureStory {
            grid-template-columns: 1fr;
          }

          .hero h1 {
            font-size: 44px;
          }
        }
      `}</style>
    </section>
  );
}
